### ISSUE TITLE
MPQC without new features fails to build 

### ISSUE THREAD

**Issue by calewis** [ValeevGroup/mpqc#10]
In file included from /Users/evaleev/bamboo-home/xml-data/build-dir/15892481/MPQC-MPQC4STANDARD-GCCBUILDCHECK0/src/lib/chemistry/qc/basis/inttraits.cc:29:
/Users/evaleev/bamboo-home/xml-data/build-dir/15892481/MPQC-MPQC4STANDARD-GCCBUILDCHECK0/src/lib/chemistry/qc/basis/inttraits.h:62:62: error: non-type template argument of type 'OneBodyOperSet::type' cannot be converted to a value of type 'TwoBodyOperSet::type'
      typedef typename detail::TwoBodyEvalCreator<NumCenters,Type>::value TwoBodyEvalCreator;
                                                             ^~~~
/Users/evaleev/bamboo-home/xml-data/build-dir/15892481/MPQC-MPQC4STANDARD-GCCBUILDCHECK0/src/lib/chemistry/qc/basis/integral.h:104:50: note: template parameter is declared here
  template <int NumCenters, TwoBodyOperSet::type Type> struct TwoBodyEvalCreator;
                                                 ^
In file included from /Users/evaleev/bamboo-home/xml-data/build-dir/15892481/MPQC-MPQC4STANDARD-GCCBUILDCHECK0/src/lib/chemistry/qc/basis/inttraits.cc:29:
/Users/evaleev/bamboo-home/xml-data/build-dir/15892481/MPQC-MPQC4STANDARD-GCCBUILDCHECK0/src/lib/chemistry/qc/basis/inttraits.h:62:69: error: expected a qualified name after 'typename'
      typedef typename detail::TwoBodyEvalCreator<NumCenters,Type>::value TwoBodyEvalCreator;
                                                                    ^
/Users/evaleev/bamboo-home/xml-data/build-dir/15892481/MPQC-MPQC4STANDARD-GCCBUILDCHECK0/src/lib/chemistry/qc/basis/inttraits.h:62:74: error: expected ';' at end of declaration
      typedef typename detail::TwoBodyEvalCreator<NumCenters,Type>::value TwoBodyEvalCreator;
                                                                         ^
                                                                         ;
/Users/evaleev/bamboo-home/xml-data/build-dir/15892481/MPQC-MPQC4STANDARD-GCCBUILDCHECK0/src/lib/chemistry/qc/basis/inttraits.h:63:14: error: use of undeclared identifier 'TwoBodyEvalCreator'
      return TwoBodyEvalCreator::eval(factory,params);

**Comment by evaleev** [comment]
fixed in 671e7fd1618a1a6833e39dcff73cab104900a738
