### ISSUE TITLE
MPQC3 r12 calculation gives wrong result for VT2 term at multiple thread 

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/mpqc#29]
This happens when using MPQC3 pt2r12 module. The result for VT2 term is wrong when running at multiple thread. It goes back to normal when using density fitting.

Input file: [ch2.pt2r12.dat] (https://www.dropbox.com/s/7gmbvc0waybjyo9/ch2.pt2r12.dat?dl=0), [ch2.pt2r12.rmd2.dat]  (https://www.dropbox.com/s/a8uap4hvbm4ih9r/ch2.pt2r12.rdm2.dat?dl=0)

command: 
`pt2r12 -prefix ch2 -obs cc-pVDZ -cabs cc-pVDZ-F12-CABS -singles true -partitionH dyall_1  -threadgrp '<PthreadThreadGrp>:(num_threads=2)'` will give the wrong result in VT2 term. See the output file: [wrong.output](https://www.dropbox.com/s/3jzwt8wv4xeeupo/wrong.output?dl=0)

if use density fitting, 
`pt2r12 -prefix ch2 -obs cc-pVDZ -cabs cc-pVDZ-F12-CABS -dfbs cc-pVTZ-RI -singles true -partitionH dyall_1  -threadgrp '<PthreadThreadGrp>:(num_threads=2)'` will give the corret result. See the output file: [correct.output] (https://www.dropbox.com/s/44bq7l34nfvrcdz/correct.output?dl=0)

I did not notice this bug until now because I usually use density fitting. My hypothesis is that something is wrong in the term `"R12_m1_G12[0]"` which is computed for VT2 term.

Please give me some hints. I will try to solve it.

**Comment by evaleev** [comment]
GaussianGmEval in libint2 is not reentrant. I'm working on this.
