### ISSUE TITLE
--with-mpicc doesn't do intelligent things w.r.t. compiler detection

### ISSUE THREAD

**Issue by jeffhammond** [ValeevGroup/mpqc#3]
If I saw MPICC=mpixlc_r, why does CMake give me CC=/soft/compilers/ibmcmp-may2013/vac/bg/12.1/bin/cc, CXX=/usr/bin/c++, and FC=/usr/bin/gfortran?  The latter two aren't even cross-compilers.

At the very least, CC=$MPICC should be respected.  The scenarios where people want CC and MPICC to be different are almost exclusively stupid.

Obviously, I know how to solve this, but I consider this a CMake fail if nothing else.

[jhammond@vestalac1 build-xlc]$ ll
total 0
[jhammond@vestalac1 build-xlc]$ ../configure --mpicc=mpixlc_r --lapack="-L/soft/compilers/ibmcmp-may2013/xlmass/bg/7.3/bglib64 -lmass -L/soft/libraries/alcf/current/xl/LAPACK/lib -llapack -L/soft/libraries/essl/current/essl/5.1/lib64 -lesslbg -L/soft/compilers/ibmcmp-may2013/xlf/bg/14.1/bglib64 -lxlf90_r -L/soft/compilers/ibmcmp-may2013/xlsmp/bg/3.1/bglib64 -lxlsmp -lxlopt -lxlfmath -lxl -Wl,--allow-multiple-definition" --prefix=$HOME/MPQC/git/install-xlc
Using CMake /soft/buildtools/cmake/2.8.11.1/bin/cmake
+ rm -fr CMakeFiles CMakeCache.txt
+ eval /soft/buildtools/cmake/2.8.11.1/bin/cmake -DMPI_C_COMPILER=mpixlc_r '-DLAPACK_LIBRARIES="-L/soft/compilers/ibmcmp-may2013/xlmass/bg/7.3/bglib64' -lmass -L/soft/libraries/alcf/current/xl/LAPACK/lib -llapack -L/soft/libraries/essl/current/essl/5.1/lib64 -lesslbg -L/soft/compilers/ibmcmp-may2013/xlf/bg/14.1/bglib64 -lxlf90_r -L/soft/compilers/ibmcmp-may2013/xlsmp/bg/3.1/bglib64 -lxlsmp -lxlopt -lxlfmath -lxl '-Wl,--allow-multiple-definition"' -DCMAKE_INSTALL_PREFIX=/home/jhammond/MPQC/git/install-xlc -DCMAKE_BUILD_TYPE=Release ..
++ /soft/buildtools/cmake/2.8.11.1/bin/cmake -DMPI_C_COMPILER=mpixlc_r '-DLAPACK_LIBRARIES=-L/soft/compilers/ibmcmp-may2013/xlmass/bg/7.3/bglib64 -lmass -L/soft/libraries/alcf/current/xl/LAPACK/lib -llapack -L/soft/libraries/essl/current/essl/5.1/lib64 -lesslbg -L/soft/compilers/ibmcmp-may2013/xlf/bg/14.1/bglib64 -lxlf90_r -L/soft/compilers/ibmcmp-may2013/xlsmp/bg/3.1/bglib64 -lxlsmp -lxlopt -lxlfmath -lxl -Wl,--allow-multiple-definition' -DCMAKE_INSTALL_PREFIX=/home/jhammond/MPQC/git/install-xlc -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is XL 12.1.0
-- The CXX compiler identification is GNU 4.4.6
-- Check for working C compiler: /soft/compilers/ibmcmp-may2013/vac/bg/12.1/bin/cc
-- Check for working C compiler: /soft/compilers/ibmcmp-may2013/vac/bg/12.1/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The Fortran compiler identification is GNU
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Performing Test HAVE_CXX_AUTO
-- Performing Test HAVE_CXX_AUTO - Failed
-- Performing Test HAVE_STD_ARRAY
-- Performing Test HAVE_STD_ARRAY - Failed
-- Performing Test HAVE_CXX_RESTRICT
-- Performing Test HAVE_CXX_RESTRICT - Failed
-- Performing Test HAVE_CXX___RESTRICT__
-- Performing Test HAVE_CXX___RESTRICT__ - Success

**Comment by evaleev** [comment]
resolved by 2c5ff3d36ca1802d6ebb4bf60df262b93b441fd1
