### ISSUE TITLE
Molecule set point group failed

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/mpqc#34]
The point group set in Molecule class is giving error for certain geometry.

Here is the input from pt2r12.dat
   1      0.000000000000      1.870882680830      0.810202552477
   6      0.000000000000     -0.010330501554     -0.001551090982
   1      0.000000000000     -1.860552181165      0.805741774591
 -1.0 -1.0 -1.0 -1.0
 Cs
 a'  a"

error message:
terminate called after throwing an instance of 'sc::SCException'
  what():  exception:   SCException
description: cleanup: couldn't find atom
location:    /hyades/home/valeev/pchong/Development/source/mpqc/src/lib/chemistry/molecule/molecule.cc:1044
class:       Molecule
backtrace:
couldn't find atom at { 0.00000  1.87088 -0.81020}
transforming uniq atom 0 at { 0.00000  1.87088  0.81020}
with symmetry op 1:
        1          2          3
  1   1.0000000  0.0000000  0.0000000
  2   0.0000000  1.0000000  0.0000000
  3   0.0000000  0.0000000 -1.0000000

The backtrace:

0  __cxa_throw () at ../../../../gcc-4.8.3/libstdc++-v3/libsupc++/eh_throw.cc:62
1  0x00000000014ea3b9 in sc::Molecule::cleanup_molecule(double) ()
    at /hyades/home/valeev/pchong/Development/source/mpqc/src/lib/chemistry/molecule/molecule.cc:1053
2  0x00000000014e6f59 in sc::Molecule::set_point_group(sc::Ref<sc::PointGroup> const&, double) ()
    at /hyades/home/valeev/pchong/Development/source/mpqc/src/lib/chemistry/molecule/molecule.cc:548
3  0x00000000048c98f2 in sc::ExternMOInfo::ExternMOInfo(std::basic_string<char, std::char_traits<char>, std::allocator<char> >, sc::Ref<sc::Integral>, std::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
    at /hyades/home/valeev/pchong/Development/source/mpqc/src/lib/extern/moinfo/moinfo.cc:163
4  0x000000000179b65e in sc::MolcasPT2R12::initialize() ()

**Comment by pchong90** [comment]
never mind, the bug is from molcas

**Comment by evaleev** [comment]
Is this a real issue?

On Fri, Feb 6, 2015 at 5:16 PM, Chong Peng <notifications@github.com> wrote:

> Reopened #34 <https://github.com/ValeevGroup/mpqc/issues/34>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ValeevGroup/mpqc/issues/34#event-231798086>.
>



-- 
web: valeyev.net

**Comment by pchong90** [comment]
Yes, I am trying to get gdb to work on Hyades to see the details.
