### ISSUE TITLE
MPQC  xml.cc fails to compile.

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/mpqc#35]
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/xml.cc:30:
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/xml.h:29:
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/consumableresources.h:36:
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/keyval/keyval.h:40:
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/class/class.h:41:
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/ref/ref.h:617:15: error: cannot
      initialize object parameter of type 'sc::RefCount' with an expression of type
      'sc::XMLWriter'
              DO_REF_UNMANAGE(cr);
              ^~~~~~~~~~~~~~~~~~~
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/ref/ref.h:145:29: note: expanded
      from macro 'DO_REF_UNMANAGE'
#define DO_REF_UNMANAGE(p) ((p)->unmanage())
                            ^~~
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/ref/ref.h:609:7: note: in
      instantiation of member function 'sc::Ref<sc::XMLWriter>::assign_pointer' requested here
      assign_pointer(cr);
      ^
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/xmlwriter.h:714:37: note: in
      instantiation of member function 'sc::Ref<sc::XMLWriter>::operator=' requested here
          XMLWriter::current_writer = 0;
                                    ^
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/xmlwriter.h:692:3: note: in
      instantiation of function template specialization
      'sc::boost_param_default_699end_xml_context<void, boost::parameter::aux::empty_arg_list,
      char const[23]>' requested here
  BOOST_PARAMETER_FUNCTION(
  ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:937:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION'
    BOOST_PARAMETER_FUNCTION_AUX(                                       \
    ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:933:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION_AUX'
    BOOST_PARAMETER_FUNCTION_DEFAULT_LAYER(name, args, 0, 0, tag_namespace)
    ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:911:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION_DEFAULT_LAYER'
    BOOST_PARAMETER_FUNCTION_DEFAULT_LAYER_AUX( \
    ^
note: (skipping 19 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/local/Cellar/boost/1.57.0/include/boost/preprocessor/cat.hpp:22:32: note: expanded from macro
      'BOOST_PP_CAT'
#    define BOOST_PP_CAT(a, b) BOOST_PP_CAT_I(a, b)
                               ^
/usr/local/Cellar/boost/1.57.0/include/boost/preprocessor/cat.hpp:29:34: note: expanded from macro
      'BOOST_PP_CAT_I'
#    define BOOST_PP_CAT_I(a, b) a ## b
                                 ^
<scratch space>:159:1: note: expanded from here
boost_param_default_699end_xml_context
^
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/xmlwriter.h:692:3: note: in
      instantiation of function template specialization
      'sc::boost_param_default_699end_xml_context<void, boost::parameter::aux::empty_arg_list>'
      requested here
  BOOST_PARAMETER_FUNCTION(
  ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:937:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION'
    BOOST_PARAMETER_FUNCTION_AUX(                                       \
    ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:933:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION_AUX'
    BOOST_PARAMETER_FUNCTION_DEFAULT_LAYER(name, args, 0, 0, tag_namespace)
    ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:911:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION_DEFAULT_LAYER'
    BOOST_PARAMETER_FUNCTION_DEFAULT_LAYER_AUX( \
    ^
note: (skipping 23 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/local/Cellar/boost/1.57.0/include/boost/preprocessor/cat.hpp:22:32: note: expanded from macro
      'BOOST_PP_CAT'
#    define BOOST_PP_CAT(a, b) BOOST_PP_CAT_I(a, b)
                               ^
/usr/local/Cellar/boost/1.57.0/include/boost/preprocessor/cat.hpp:29:34: note: expanded from macro
      'BOOST_PP_CAT_I'
#    define BOOST_PP_CAT_I(a, b) a ## b
                                 ^
<scratch space>:70:1: note: expanded from here
boost_param_default_699end_xml_context
^
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/xmlwriter.h:692:3: note: in
      instantiation of function template specialization
      'sc::boost_param_default_699end_xml_context<void, boost::parameter::aux::empty_arg_list>'
      requested here
  BOOST_PARAMETER_FUNCTION(
  ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:937:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION'
    BOOST_PARAMETER_FUNCTION_AUX(                                       \
    ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:933:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION_AUX'
    BOOST_PARAMETER_FUNCTION_DEFAULT_LAYER(name, args, 0, 0, tag_namespace)
    ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:911:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION_DEFAULT_LAYER'
    BOOST_PARAMETER_FUNCTION_DEFAULT_LAYER_AUX( \
    ^
note: (skipping 3 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/local/Cellar/boost/1.57.0/include/boost/preprocessor/cat.hpp:22:32: note: expanded from macro
      'BOOST_PP_CAT'
#    define BOOST_PP_CAT(a, b) BOOST_PP_CAT_I(a, b)
                               ^
/usr/local/Cellar/boost/1.57.0/include/boost/preprocessor/cat.hpp:29:34: note: expanded from macro
      'BOOST_PP_CAT_I'
#    define BOOST_PP_CAT_I(a, b) a ## b
                                 ^
<scratch space>:134:1: note: expanded from here
boost_param_default_699end_xml_context
^
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/xmlwriter.h:692:3: note: in
      instantiation of function template specialization
      'sc::boost_param_implend_xml_context<boost::parameter::aux::empty_arg_list>' requested here
  BOOST_PARAMETER_FUNCTION(
  ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:937:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION'
    BOOST_PARAMETER_FUNCTION_AUX(                                       \
    ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:928:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION_AUX'
    BOOST_PARAMETER_FUNCTION_FWD_FUNCTIONS(                                  \
    ^
/usr/local/Cellar/boost/1.57.0/include/boost/parameter/preprocessor.hpp:487:5: note: expanded from
      macro 'BOOST_PARAMETER_FUNCTION_FWD_FUNCTIONS'
    BOOST_PARAMETER_FUNCTION_FWD_FUNCTIONS0( \
    ^
note: (skipping 20 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/local/Cellar/boost/1.57.0/include/boost/preprocessor/cat.hpp:22:32: note: expanded from macro
      'BOOST_PP_CAT'
#    define BOOST_PP_CAT(a, b) BOOST_PP_CAT_I(a, b)
                               ^
/usr/local/Cellar/boost/1.57.0/include/boost/preprocessor/cat.hpp:29:34: note: expanded from macro
      'BOOST_PP_CAT_I'
#    define BOOST_PP_CAT_I(a, b) a ## b
                                 ^
<scratch space>:5:1: note: expanded from here
boost_param_implend_xml_context
^
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/xml.cc:30:
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/xml.h:29:
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/misc/consumableresources.h:36:
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/keyval/keyval.h:40:
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/class/class.h:41:
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/util/ref/ref.h:620:11: error: cannot
      initialize object parameter of type 'sc::RefCount' with an expression of type
      'sc::XMLWriter'
          cr->reference();
          ^~
8 errors generated.

**Comment by evaleev** [comment]
Please provide your configure command

**Comment by pchong90** [comment]
#!/bin/bash

export CXX=mpicxx
export CC=mpicc
export CXXFLAGS="-std=c++11 -O3"
export LDFLAGS="-Wl,-no_pie"

export INSTALLDIR=/Users/ChongPeng/Workspace/Development/install/mpqc3_clang/

/Users/ChongPeng/Workspace/Development/source/mpqc/configure \
    --prefix=${INSTALLDIR} \
    --mpicc=${CC} \
    --lapack="-framework Accelerate" \
    --libint="/Users/ChongPeng/Workspace/Development/install/libint_clang" \
    --boost="/usr/local/Cellar/boost/1.57.0" \
    --search="/Users/ChongPeng/Workspace/Development/install/tiledarray-clang" \
    --ci=false \
    -DMPQC_NEW_FEATURES=1 \

**Comment by evaleev** [comment]
please try omitting --boost

**Comment by pchong90** [comment]
Yes, it builds boost 1.55.0 and it compiles.
