### ISSUE TITLE
HAVE_POSIX_SPAWN macro not defined corretly?

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/mpqc#37]
it is defined [here] (https://github.com/ValeevGroup/mpqc/blob/master/src/lib/mpqc_config.h.in#L119).

However, when I use
```
#if HAVE_POSIX_SPAWN
...
#endif
```
it is false even though there is spawn.h in the system.

**Comment by evaleev** [comment]
It seems that posix_spawn is missing from cmake files
