### ISSUE TITLE
MPQC R12 Integral file not closed after each calculation.

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/mpqc#38]
The opened file will cumulate repeatedly until the program exits. 

Here is an example of opened files at second iteration of calculation. The highlighted file is where the repeat starts.

I am thinking to clean this file name in the destructor of the call object. However, I don't know where this value are stored. Please let me know where this file names are stored so I can try to clean them in the destructor.

![screen shot 2015-04-21 at 11 49 35 am](https://cloud.githubusercontent.com/assets/3442099/7256353/8f5bc1f4-e81c-11e4-95d7-9cc6c20a42cc.png)

**Comment by evaleev** [comment]
These files are controlled by their respective owners ... calling WavefunctionWorld::obsolete() should pure the registries that "own" these files. Since MolcasPT2R12 "owns" its WavefunctionWorld object (it creates it) it is the rightful caller of obsolete().

**Comment by pchong90** [comment]
I changed the code and `WavefunctionWorld::obsolete() ` is called at each iteration. Still not fix the problem. Could not figure out where to clean the files.

**Comment by evaleev** [comment]
[having a look]

**Comment by evaleev** [comment]
it still appears that there are hanging handles. hold up, I'll dig deeper.

**Comment by pchong90** [comment]
Thank you. This helps a lot.
