### ISSUE TITLE
PSI3 auto-build failed on MAC

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/mpqc#42]
[  0%] Performing configure step for 'psi3'
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: /System/Library/Frameworks/Ruby.framework/Headers/ruby
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: /System/Library/Frameworks/Accelerate.framework /System/Library/Frameworks/Accelerate.framework
checking build system type... Invalid configuration `/System/Library/Frameworks/Ruby.framework/Headers/ruby': machine `/System/Library/Frameworks/Ruby.framework/Headers/ruby' not recognized
configure: error: /bin/sh bin/config.sub /System/Library/Frameworks/Ruby.framework/Headers/ruby failed
make[3]: *** [external/build/psi3/src/psi3-stamp/psi3-configure] Error 1
make[2]: *** [CMakeFiles/psi3.dir/all] Error 2
make[1]: *** [src/bin/mpqc/CMakeFiles/mpqc.dir/rule] Error 2
make: *** [mpqc] Error 2
configure file
```
-DLIBINT=/path_to_libint
-DBOOST=/path_to_boost
-DMPQC_CI=false
-DCMAKE_CXX_FLAGS=-std=c++11
-DMPI_C_COMPILER=clang
-DMPQC_R12=true
-DPSI3=on
```

**Comment by mbanck** [comment]
If fails in a similar fashion on Linux for me:

```
[  0%] Performing configure step for 'psi3'
cd "/home/mbanck/debian/debichem/packages/mpqc3-0.0~git20150912/obj-x86_64-linux-gnu/external/build/psi3/src/psi3" && /bin/bash ./configure "--prefix=/home/mbanck/debian/debichem/packages/mpqc3-0.0~git20150912/obj-x86_64-linux-gnu/external/build/psi3" --with-cc=/usr/bin/cc CFLAGS= --with-cxx=/usr/bin/c++ "CXXFLAGS=-g -O2 -std=c++11 " "LDFLAGS= -lpthread  " --with-fc=/usr/bin/gfortran --with-blas=/usr/lib/liblapack.so "/usr/lib/libblas.so /usr/lib/libblas.so"
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: /usr/lib/libblas.so /usr/lib/libblas.so
checking build system type... config.sub: too many arguments
Try `config.sub --help' for more information.
configure: error: /bin/sh bin/config.sub /usr/lib/libblas.so /usr/lib/libblas.so failed
CMakeFiles/psi3.dir/build.make:105: recipe for target 'external/build/psi3/src/psi3-stamp/psi3-configure' failed
make[3]: *** [external/build/psi3/src/psi3-stamp/psi3-configure] Error 1
make[3]: Leaving directory '/home/mbanck/debian/debichem/packages/mpqc3-0.0~git20150912/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:962: recipe for target 'CMakeFiles/psi3.dir/all' failed
make[2]: *** [CMakeFiles/psi3.dir/all] Error 2
```

**Comment by evaleev** [comment]
these issues likely due to insufficient quotes ... hard to troubleshoot better without more details. 31436d62e577503d6a4f758c1f258472fe47c61f should help configure-based use, direct use of cmake should not suffer from this issue if LAPACK_LIBRARIES and LAPACK_LINKER_FLAGS were specified correctly.
