### ISSUE TITLE
ARMCI library from external/ARMCI no longer available and support for external libs broken

### ISSUE THREAD

**Issue by mbanck** [ValeevGroup/mpqc#43]
If no ARMCI is found (more on that later), external/armci.tar.gz gets unpackaged and built. external/ARMCI mentions this reference:

```
    # set(ARMCI_URL http://www.hdfgroup.org/ftp/ARMCI/current/src/armci-1.8.10-patch1.tar.gz)
    # set(ARMCI_URL_HASH MD5=2147a289fb33c887464ad2b6c5a8ae4c)
```

However, hdfgroup.org seems to no longer provide that tarball. If there is any other other upstream, the documentation should be updated, but at least on Google the only hit for "armci armci-1.8.10-patch1.tar.gz" is the MPQC github repository.

Further, if I try to use ARMCI from Global Arrays, the CMake logic in external/ARMCI does not let me.  It checks for a HAVE_ARMCI variable that does not get set by cmake/modules/FindARMCI.cmake. I manage to get ARMCI detected if I apply the following patch:

```
diff --git a/external/ARMCI b/external/ARMCI
index 0f8b79f..7670d4b 100644
--- a/external/ARMCI
+++ b/external/ARMCI
@@ -12,6 +12,9 @@ if (DEFINED ARMCI)
   find_package(ARMCI)
   if (NOT ARMCI_FOUND)
     message(FATAL_ERROR "ARMCI not found in ${ARMCI_PREFIX}")
+  else()
+    message(STATUS "ARMCI found in ${ARMCI_PREFIX}")
+    set(HAVE_ARMCI TRUE)
   endif()
 endif()
```

Not sure whether this is the right approach, though; when I try to run jobs compiled with GA's ARMCI, I get crashes.

**Comment by evaleev** [comment]
I do not believe we ever tested the use of standalone ARMCI from PNNL or the version from GA. The included ARMCI (armci.tar.gz) is the implementation of the API on top of MPI from Argonne. That was the only version we tested.

P.S. I'm trying to validate that the jobs that use ARMCI (parallel configuration interaction) work correctly in parallel.

**Comment by asadchev** [comment]
is that addressed to me by chance?

**Comment by evaleev** [comment]
@asadchev If your memory goes back that far, sure. What what the issue between ARMCI-MPI and HDF5?

update: parallel CI works using included armci .

**Comment by jeffhammond** [comment]
@evaleev If you only use ARMCI in the form of ARMCI-MPI, it would make a lot of sense to manually inline those ARMCI calls, i.e. just call MPI-3 RMA directly.  If it is something you are interested in, I can take a pass at doing it, since I know the translation pretty well :-)

**Comment by jeffhammond** [comment]
@evaleev In any case, please use the ARMCI-MPI Git repo `mpi3rma` branch if you use anything.  I have no idea what version the HDF folks were shipping, but if it is based on `master`, it's only use MPI-2 RMA.

We are working towards a proper release structure for ARMCI-MPI and moving MPI-3 RMA into master.  That it hasn't happened already is my fault.

**Comment by evaleev** [comment]
@jeffhammond no worries. this issue referred to the experimental code in the "old" MPQC that will be transitioned to TiledArray/MADNESS backend in due time. "New" MPQC will not have the ARMCI dependence.

**Comment by jeffhammond** [comment]
Okay thanks.  I have been discussing ARMCI-dependent codes with @mbanck and am hoping to reduce their number :-)

**Comment by asadchev** [comment]
sorry for late response.
As far as i remember there were no issues between hdf5 and armci, they
should have been pretty orthogonal.
