### ISSUE TITLE
check0 does not run f12 tests even with -DHAVE_R12 and libint2

### ISSUE THREAD

**Issue by mbanck** [ValeevGroup/mpqc#46]
I have recently started building with libint2, and cmake added -DHAVE_R12 to the compile flags and mbptr12 et al. get built (which was not the case before) so I believe that is fine.

However, if I run the usual "make check0", the exact same number of tests as before is run, while I assumed additional f12 tests would be added.

I checked that the `ifeq (@MAKE_ASSUME_R12@,yes)` in tests/check.mk.in gets expanded to `ifeq (yes, yes)` in the object tree. What I am not really clear about are those `$(MPQCRUN_INTEGRAL)` checks - is this something that needs to be set in some environment variable or elsewhere, or is this supposed to be automatically set if e.g. libint2 is used?

**Comment by evaleev** [comment]
the r12/f12 capability was always considered not part of core MPQC, hence you had to specify MPQCRUN_ARGS manually to run libint2-dependent tests. Now all checks will try to use all available integral factories and f12 tests should run as part of make checkX
